"""initial schema

Revision ID: 237d4a16ae83
Revises: 
Create Date: 2026-07-23 14:14:26.171116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237d4a16ae83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room_type', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('badge', sa.String(), nullable=False),
    sa.Column('footnote', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('tag_count', sa.Integer(), nullable=False),
    sa.Column('metric_config', sa.JSON(), nullable=False),
    sa.Column('adapter_type', sa.String(), nullable=False),
    sa.Column('adapter_config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_room_type'), 'rooms', ['room_type'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_occurred_at'), 'audit_log', ['occurred_at'], unique=False)
    op.create_table('harvests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('strain', sa.String(), nullable=False),
    sa.Column('source_room_id', sa.String(), nullable=False),
    sa.Column('drying_room_id', sa.String(), nullable=True),
    sa.Column('wet_weight_g', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drying_room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['source_room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('physical_counts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('counted_value', sa.Integer(), nullable=False),
    sa.Column('system_value_at_time', sa.Integer(), nullable=False),
    sa.Column('counted_by', sa.String(), nullable=False),
    sa.Column('counted_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_physical_counts_room_id'), 'physical_counts', ['room_id'], unique=False)
    op.create_table('plant_batches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('batch_type', sa.String(), nullable=False),
    sa.Column('strain', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('planted_date', sa.Date(), nullable=False),
    sa.Column('source_batch_id', sa.String(), nullable=True),
    sa.Column('untracked_count', sa.Integer(), nullable=False),
    sa.Column('tracked_count', sa.Integer(), nullable=False),
    sa.Column('packaged_count', sa.Integer(), nullable=False),
    sa.Column('harvested_count', sa.Integer(), nullable=False),
    sa.Column('destroyed_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['source_batch_id'], ['plant_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_plant_batches_room_id'), 'plant_batches', ['room_id'], unique=False)
    op.create_table('readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readings_metric'), 'readings', ['metric'], unique=False)
    op.create_index(op.f('ix_readings_room_id'), 'readings', ['room_id'], unique=False)
    op.create_index(op.f('ix_readings_ts'), 'readings', ['ts'], unique=False)
    op.create_table('waste_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('waste_type', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('weight_g', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waste_events_room_id'), 'waste_events', ['room_id'], unique=False)
    op.create_table('harvest_weight_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('harvest_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('weight_g', sa.Float(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['harvest_id'], ['harvests.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harvest_weight_logs_harvest_id'), 'harvest_weight_logs', ['harvest_id'], unique=False)
    op.create_table('packages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('harvest_id', sa.String(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('weight_g', sa.Float(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('is_production_batch', sa.Boolean(), nullable=False),
    sa.Column('is_donation', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['harvest_id'], ['harvests.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_room_id'), 'packages', ['room_id'], unique=False)
    op.create_table('plants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('strain', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('growth_phase', sa.String(), nullable=False),
    sa.Column('planted_date', sa.Date(), nullable=False),
    sa.Column('tagged_date', sa.Date(), nullable=False),
    sa.Column('mother_plant_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['plant_batches.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plants_room_id'), 'plants', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plants_room_id'), table_name='plants')
    op.drop_table('plants')
    op.drop_index(op.f('ix_packages_room_id'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_harvest_weight_logs_harvest_id'), table_name='harvest_weight_logs')
    op.drop_table('harvest_weight_logs')
    op.drop_index(op.f('ix_waste_events_room_id'), table_name='waste_events')
    op.drop_table('waste_events')
    op.drop_index(op.f('ix_readings_ts'), table_name='readings')
    op.drop_index(op.f('ix_readings_room_id'), table_name='readings')
    op.drop_index(op.f('ix_readings_metric'), table_name='readings')
    op.drop_table('readings')
    op.drop_index(op.f('ix_plant_batches_room_id'), table_name='plant_batches')
    op.drop_table('plant_batches')
    op.drop_index(op.f('ix_physical_counts_room_id'), table_name='physical_counts')
    op.drop_table('physical_counts')
    op.drop_table('harvests')
    op.drop_index(op.f('ix_audit_log_occurred_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_rooms_room_type'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
