"""add facility secrets for in-app credential management

Revision ID: 2d2a06d8844a
Revises: 58c9f5441db9
Create Date: 2026-08-05 16:15:57.980054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d2a06d8844a'
down_revision: Union[str, Sequence[str], None] = '58c9f5441db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility_secrets',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # Note: autogenerate also detected the same pre-existing, unrelated
    # packages.source_package_id FK drift flagged in 58c9f5441db9 — still not this
    # migration's concern, deliberately not included here.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facility_secrets')
    # ### end Alembic commands ###
