"""add audit log hash chaining

Revision ID: 492637f91c0e
Revises: fa3fa79c0a59
Create Date: 2026-07-23 15:27:30.476237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '492637f91c0e'
down_revision: Union[str, Sequence[str], None] = 'fa3fa79c0a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('prev_hash', sa.String(), nullable=False))
    op.add_column('audit_log', sa.Column('entry_hash', sa.String(), nullable=False))
    op.create_index(op.f('ix_audit_log_entry_hash'), 'audit_log', ['entry_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_entry_hash'), table_name='audit_log')
    op.drop_column('audit_log', 'entry_hash')
    op.drop_column('audit_log', 'prev_hash')
    # ### end Alembic commands ###
