"""add room adapters for multiple sensor adapters per room

Revision ID: 58c9f5441db9
Revises: 3a7195d4e90e
Create Date: 2026-07-31 10:44:06.845113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c9f5441db9'
down_revision: Union[str, Sequence[str], None] = '3a7195d4e90e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_adapters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('adapter_type', sa.String(), nullable=False),
    sa.Column('adapter_config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_adapters_room_id'), 'room_adapters', ['room_id'], unique=False)
    # Note: autogenerate also detected a missing self-referential FK on
    # packages.source_package_id (pre-existing drift, unrelated to this migration —
    # SQLite's ALTER TABLE can't add a FK constraint without a full batch table
    # rebuild, a bigger/riskier change than this migration's actual purpose).
    # Deliberately not included here; the column and its behavior are unaffected.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_adapters_room_id'), table_name='room_adapters')
    op.drop_table('room_adapters')
    # ### end Alembic commands ###
