"""add package processing chain and lab tests

Revision ID: 6fcee4b85466
Revises: a243d20e94fb
Create Date: 2026-07-27 12:13:39.837525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fcee4b85466'
down_revision: Union[str, Sequence[str], None] = 'a243d20e94fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_tests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('package_id', sa.String(), nullable=False),
    sa.Column('lab_name', sa.String(), nullable=False),
    sa.Column('test_type', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('thc_pct', sa.Float(), nullable=True),
    sa.Column('cbd_pct', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('tested_at', sa.Date(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('recorded_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_tests_package_id'), 'lab_tests', ['package_id'], unique=False)
    op.add_column('packages', sa.Column('source_package_id', sa.String(), nullable=True))
    op.add_column('packages', sa.Column('process_method', sa.String(), nullable=True))
    op.add_column('packages', sa.Column('process_yield_pct', sa.Float(), nullable=True))
    # No op.create_foreign_key here: SQLite can't ALTER TABLE ADD CONSTRAINT without
    # batch mode (full table rebuild), and this project already doesn't rely on
    # SQLite enforcing foreign keys at the DB level (see db.py) — the column and the
    # ORM-level relationship are what matter for how this project actually uses it.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'process_yield_pct')
    op.drop_column('packages', 'process_method')
    op.drop_column('packages', 'source_package_id')
    op.drop_index(op.f('ix_lab_tests_package_id'), table_name='lab_tests')
    op.drop_table('lab_tests')
    # ### end Alembic commands ###
