"""add cross-device relay support

Revision ID: a243d20e94fb
Revises: 492637f91c0e
Create Date: 2026-07-23 18:38:49.392391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a243d20e94fb'
down_revision: Union[str, Sequence[str], None] = '492637f91c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relay_cursors',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.add_column('audit_log', sa.Column('origin_device_id', sa.String(), nullable=True))
    op.add_column('audit_log', sa.Column('origin_entry_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_log', 'origin_entry_hash')
    op.drop_column('audit_log', 'origin_device_id')
    op.drop_table('relay_cursors')
    # ### end Alembic commands ###
