"""add reading rollups

Revision ID: eb1cfb89f9ec
Revises: 237d4a16ae83
Create Date: 2026-07-23 14:17:31.699521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb1cfb89f9ec'
down_revision: Union[str, Sequence[str], None] = '237d4a16ae83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_rollups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('bucket_start', sa.DateTime(), nullable=False),
    sa.Column('avg_value', sa.Float(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'metric', 'bucket_start', name='uq_reading_rollup_bucket')
    )
    op.create_index(op.f('ix_reading_rollups_bucket_start'), 'reading_rollups', ['bucket_start'], unique=False)
    op.create_index(op.f('ix_reading_rollups_metric'), 'reading_rollups', ['metric'], unique=False)
    op.create_index(op.f('ix_reading_rollups_room_id'), 'reading_rollups', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reading_rollups_room_id'), table_name='reading_rollups')
    op.drop_index(op.f('ix_reading_rollups_metric'), table_name='reading_rollups')
    op.drop_index(op.f('ix_reading_rollups_bucket_start'), table_name='reading_rollups')
    op.drop_table('reading_rollups')
    # ### end Alembic commands ###
