"""add room poll health tracking

Revision ID: fa3fa79c0a59
Revises: 30824cdb12fd
Create Date: 2026-07-23 15:11:02.104529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa3fa79c0a59'
down_revision: Union[str, Sequence[str], None] = '30824cdb12fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('last_poll_at', sa.DateTime(), nullable=True))
    op.add_column('rooms', sa.Column('last_poll_error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'last_poll_error')
    op.drop_column('rooms', 'last_poll_at')
    # ### end Alembic commands ###
